from pathlib import Path

import matplotlib.pyplot as plt
from numpy.strings import center
import pandas as pd
import streamlit as st

from components.kpi_cards import show_kpi_cards
from components.page_header import show_page_header
from components.takeaway import show_takeaway

from utils.config import (
    DEFECT_CLASSIFIER_REPORTS_PATH,
    FIGURE_DPI,
    FIGURE_HEIGHT,
    FIGURE_WIDTH,
    PATCHCORE_METRICS_PATH,
)

from utils.model_metrics import (
    load_defect_classifier_reports,
)

from components.sidebar import show_sidebar
from utils.style_loader import load_css

# =========================================================
# GLOBAL APPLICATION ELEMENTS
# =========================================================
load_css()
show_sidebar()
# =========================================================
# PAGE HEADER
# =========================================================

show_page_header(
    title="PatchCore Model and Results",
    subtitle=(
        "Category-specific one-class anomaly detection, "
        "pixel-level localization and defect classification."
    ),
    icon="🚀",
)


# =========================================================
# PATH VALIDATION
# =========================================================

if not PATCHCORE_METRICS_PATH.exists():
    st.error(
        "PatchCore metrics file not found:\n\n"
        f"`{PATCHCORE_METRICS_PATH}`"
    )
    st.stop()


if not DEFECT_CLASSIFIER_REPORTS_PATH.exists():
    st.error(
        "Defect-classifier report directory not found:\n\n"
        f"`{DEFECT_CLASSIFIER_REPORTS_PATH}`"
    )
    st.stop()


# =========================================================
# DATA LOADERS
# =========================================================

@st.cache_data
def load_patchcore_metrics(
    path: str | Path,
) -> pd.DataFrame:
    """
    Load category-wise PatchCore metrics.
    """

    dataframe = pd.read_csv(path)

    required_columns = {
        "category",
        "aupro",
        "image_auroc",
        "pixel_auroc",
        "image_f1",
        "pixel_f1",
    }

    missing_columns = (
        required_columns
        - set(dataframe.columns)
    )

    if missing_columns:
        raise ValueError(
            "PatchCore metrics file is missing columns: "
            f"{sorted(missing_columns)}"
        )

    return dataframe


@st.cache_data
def load_original_defect_reports(
    reports_path: str | Path,
) -> pd.DataFrame:
    """
    Load the original cross-validation JSON reports
    generated by the defect-classifier training script.
    """

    return load_defect_classifier_reports(
        reports_path
    )


try:
    patchcore_df = load_patchcore_metrics(
        PATCHCORE_METRICS_PATH
    )

    defect_df = load_original_defect_reports(
        DEFECT_CLASSIFIER_REPORTS_PATH
    )

except (
    FileNotFoundError,
    ValueError,
    RuntimeError,
    OSError,
) as error:

    st.exception(error)
    st.stop()


# =========================================================
# SUMMARY METRICS
# =========================================================

mean_image_auroc = (
    patchcore_df["image_auroc"].mean()
)

mean_image_f1 = (
    patchcore_df["image_f1"].mean()
)

mean_pixel_auroc = (
    patchcore_df["pixel_auroc"].mean()
)

mean_pixel_f1 = (
    patchcore_df["pixel_f1"].mean()
)

mean_aupro = (
    patchcore_df["aupro"].mean()
)


show_kpi_cards(
    [
        (
            "Mean Image AUROC",
            f"{mean_image_auroc:.3f}",
        ),
        (
            "Mean Image F1",
            f"{mean_image_f1:.3f}",
        ),
        (
            "Mean Pixel AUROC",
            f"{mean_pixel_auroc:.3f}",
        ),
        (
            "Mean AUPRO",
            f"{mean_aupro:.3f}",
        ),
    ]
)


# =========================================================
# TABS
# =========================================================

tab1, tab2, tab3, tab4 = st.tabs(
    [
        "System Overview",
        "PatchCore",
        "Results",
        "Defect Classification",
    ]
)


# =========================================================
# TAB 1 — END-TO-END WORKFLOW
# =========================================================

with tab1:

    workflow_col, router_col = st.columns(
        [1.1, 1]
    )

    with workflow_col:

        st.markdown("#### End-to-End Workflow")

        st.code(
            """
Input Image
    ↓
DINOv2 Hybrid Feature
    ↓
Logistic Regression Router
    ↓
Predicted Object Category
    ↓
Category-Specific PatchCore
    ↓
Normal or Anomalous?
    ├── Normal → Stop
    └── Anomalous
          ↓
      Heatmap + Polynomial SVM
          ↓
      Defect Type
            """,
            language="text",
        )

    with router_col:

        st.markdown("#### Object Router")

        router_configuration = pd.DataFrame(
            {
                "Element": [
                    "Input",
                    "Backbone",
                    "Hybrid feature",
                    "Classifier",
                    "Categories",
                ],
                "Configuration": [
                    "518 × 518",
                    "DINOv2 ViT-L/14",
                    "2,048 dimensions",
                    "Balanced Logistic Regression",
                    "15",
                ],
            }
        )

        st.dataframe(
            router_configuration,
            use_container_width=True,
            hide_index=True,
            height=250,
        )

        st.info(
            "The router selects the category-specific PatchCore model. "
            "The reported 100% accuracy applies only to the available "
            "evaluation data."
        )

# =========================================================
# TAB 2 — DINOv2 OBJECT ROUTER
# =========================================================

with tab2:

    config_col, mechanism_col = st.columns(
        [1.05, 1]
    )

    with config_col:

        patchcore_configuration = pd.DataFrame(
            {
                "Element": [
                    "Framework",
                    "Backbone",
                    "Training data",
                    "Feature stages",
                    "Memory reduction",
                    "Models",
                    "Export",
                ],
                "Configuration": [
                    "Anomalib 2.5.0",
                    "Wide-ResNet-50-2",
                    "Category-specific train/good",
                    "Layer 2 and layer 3",
                    "Coreset subsampling",
                    "15 category-specific models",
                    "OpenVINO",
                ],
            }
        )

        st.dataframe(
            patchcore_configuration,
            use_container_width=True,
            hide_index=True,
            height=300,
        )

    with mechanism_col:

        st.markdown("#### Training")

        st.code(
            """
Normal Images
    ↓
Feature Extraction
    ↓
Local Patch Embeddings
    ↓
Coreset Subsampling
    ↓
Memory Bank
            """,
            language="text",
        )

        st.markdown("#### Inference")

        st.latex(
            r"s_i=\min_{m\in M_C}\|q_i-m\|_2"
        )

        st.caption(
            "Large nearest-neighbour distances indicate "
            "unusual local structures."
        )

    output_col, interpretation_col = st.columns(2)

    with output_col:

        inference_outputs = pd.DataFrame(
            {
                "Output": [
                    "pred_score",
                    "pred_label",
                    "anomaly_map",
                ],
                "Meaning": [
                    "Global anomaly score",
                    "Normal/anomalous decision",
                    "Spatial localization",
                ],
            }
        )

        st.dataframe(
            inference_outputs,
            use_container_width=True,
            hide_index=True,
            height=180,
        )

    with interpretation_col:

        st.success(
            "PatchCore does not reconstruct the input. It compares "
            "test patch features with the stored normal memory bank."
        )
# =========================================================
# TAB 3 — PATCHCORE
# =========================================================

with tab3:

    selected_category = st.selectbox(
        "Select category",
        options=sorted(
            patchcore_df["category"].tolist()
        ),
        key="patchcore_category",
    )

    selected_result = patchcore_df.loc[
        patchcore_df["category"] == selected_category
    ].iloc[0]

    result1, result2, result3, result4, result5 = st.columns(5)

    result1.metric(
        "AUPRO",
        f"{selected_result['aupro']:.2f}",
    )

    result2.metric(
        "Image AUROC",
        f"{selected_result['image_auroc']:.2f}",
    )

    result3.metric(
        "Pixel AUROC",
        f"{selected_result['pixel_auroc']:.2f}",
    )

    result4.metric(
        "Image F1",
        f"{selected_result['image_f1']:.2f}",
    )

    result5.metric(
        "Pixel F1",
        f"{selected_result['pixel_f1']:.2f}",
    )

    chart_col, table_col = st.columns(
        [1.25, 1]
    )

    with chart_col:

        chart_data = patchcore_df.sort_values(
            "image_auroc",
            ascending=True,
        )

        figure, axis = plt.subplots(
            figsize=(
                FIGURE_WIDTH,
                FIGURE_HEIGHT,
            ),
            dpi=FIGURE_DPI,
        )

        axis.barh(
            chart_data["category"],
            chart_data["image_auroc"],
        )

        axis.set_xlim(
            0.85,
            1.01,
        )

        axis.set_title(
            "PatchCore Image AUROC by Category",
            fontsize=11,
            fontweight="bold",
        )

        axis.set_xlabel(
            "Image AUROC",
            fontsize=9,
            fontweight="bold",
        )

        axis.tick_params(
            axis="both",
            labelsize=8,
        )

        axis.grid(
            axis="x",
            linestyle="--",
            alpha=0.3,
        )

        axis.spines["top"].set_visible(False)
        axis.spines["right"].set_visible(False)

        figure.tight_layout(
            pad=0.5
        )

        st.pyplot(
            figure,
            use_container_width=True,
        )

        plt.close(figure)

    with table_col:

        patchcore_display = patchcore_df.rename(
            columns={
                "category": "Category",
                "aupro": "AUPRO",
                "image_auroc": "Image AUROC",
                "pixel_auroc": "Pixel AUROC",
                "image_f1": "Image F1",
                "pixel_f1": "Pixel F1",
            }
        )

        st.dataframe(
            patchcore_display.style.format(
                {
                    "AUPRO": "{:.2f}",
                    "Image AUROC": "{:.2f}",
                    "Pixel AUROC": "{:.2f}",
                    "Image F1": "{:.2f}",
                    "Pixel F1": "{:.2f}",
                }
            ),
            use_container_width=True,
            hide_index=True,
            height=360,
        )

    st.info(
        f"Mean image AUROC: {mean_image_auroc:.3f} · "
        f"Mean image F1: {mean_image_f1:.3f} · "
        f"Mean pixel F1: {mean_pixel_f1:.3f}"
    )

# =========================================================
# TAB 4 — PATCHCORE RESULTS
# =========================================================

with tab4:

    st.subheader(
        "Category-Specific Defect-Type Classification"
    )

    st.markdown(
        """
        PatchCore detects whether an object is anomalous and where
        the anomaly is located. It does not assign a physical defect
        name.

        For anomalous images, a separate category-specific SVM uses
        the same 2,048-dimensional DINOv2 hybrid features.
        """
    )

    svm_configuration = pd.DataFrame(
        {
            "Element": [
                "Classifier",
                "Kernel",
                "Degree",
                "C",
                "Gamma",
                "Class weight",
                "Validation",
                "Small-dataset strategy",
            ],
            "Configuration": [
                "Support Vector Machine",
                "Polynomial",
                "5",
                "100",
                "scale",
                "balanced",
                "Stratified 5-fold cross-validation",
                "Leave-One-Out when the original sample count is below 20",
            ],
        }
    )

    st.dataframe(
        svm_configuration,
        use_container_width=True,
        hide_index=True,
    )

    mean_macro_f1 = (
        defect_df["macro_f1_mean"]
        .dropna()
        .mean()
    )

    classifier_metric1, classifier_metric2 = (
        st.columns(2)
    )

    classifier_metric1.metric(
        "Evaluated Categories",
        len(defect_df),
    )

    classifier_metric2.metric(
        "Mean Macro F1",
        f"{mean_macro_f1:.3f}",
    )

    available_columns = [
        column
        for column in [
            "category",
            "accuracy_mean",
            "macro_precision_mean",
            "macro_recall_mean",
            "macro_f1_mean",
            "macro_f1_std",
        ]
        if column in defect_df.columns
    ]

    defect_display = defect_df[
        available_columns
    ].rename(
        columns={
            "category": "Category",
            "accuracy_mean": "Accuracy",
            "macro_precision_mean":
                "Macro Precision",
            "macro_recall_mean":
                "Macro Recall",
            "macro_f1_mean":
                "Macro F1",
            "macro_f1_std":
                "Macro F1 Std",
        }
    )

    numeric_formats = {
        column: "{:.3f}"
        for column in [
            "Accuracy",
            "Macro Precision",
            "Macro Recall",
            "Macro F1",
            "Macro F1 Std",
        ]
        if column in defect_display.columns
    }

    st.dataframe(
        defect_display.style.format(
            numeric_formats,
            na_rep="—",
        ),
        use_container_width=True,
        hide_index=True,
    )

    st.divider()

    defect_chart_data = (
        defect_df
        .dropna(
            subset=["macro_f1_mean"]
        )
        .sort_values(
            "macro_f1_mean",
            ascending=True,
        )
    )

    defect_figure, defect_axis = (
        plt.subplots(
           figsize=(FIGURE_WIDTH,FIGURE_HEIGHT,)
        )
    )

    error_values = (
        defect_chart_data["macro_f1_std"]
        if "macro_f1_std"
        in defect_chart_data.columns
        else None
    )

    defect_axis.barh(
        defect_chart_data["category"],
        defect_chart_data["macro_f1_mean"],
        xerr=error_values,
        capsize=3,
    )

    defect_axis.set_xlim(0, 1.05)

    defect_axis.set_title(
        "Defect-Type Classification Macro F1",
        fontweight="bold",
    )

    defect_axis.set_xlabel(
        "Macro F1",
        fontweight="bold",
    )

    defect_axis.set_ylabel(
        "Category",
        fontweight="bold",
    )

    defect_axis.grid(
        axis="x",
        linestyle="--",
        alpha=0.3,
    )

    defect_axis.spines["top"].set_visible(False)
    defect_axis.spines["right"].set_visible(False)

    defect_figure.tight_layout()

    left_space, chart_space, right_space = st.columns(
        [1, 3, 1]
    )

    left, center, right = st.columns([1.2, 3, 1.2])
    with center:
        st.pyplot(
        defect_figure,
        use_container_width=True,
    )

    plt.close(defect_figure)

    st.warning(
        """
        Augmented images are included only in the training portion
        of each validation fold. Augmentations derived from test
        originals are excluded to prevent data leakage.

        Augmentation increases the number of training examples but
        does not create genuinely new physical defect mechanisms.
        """
    )


# =========================================================
# TAB 5 — DEFECT CLASSIFICATION
# =========================================================


# =========================================================
# FINAL SUMMARY
# =========================================================

st.divider()

st.success(
    """
    **Conclusion**

    The implemented PatchCore system achieves strong image-level
    anomaly detection across all 15 MVTec AD categories. Pixel-level
    localization is more challenging, especially when defects are
    thin, irregular or difficult to threshold precisely.

    The category-specific SVM classifiers add defect-type diagnosis,
    but their stability is limited by the small number of independent
    defect images.
    """
)